name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
          submodules: true
          lfs: false
          persist-credentials: false

    - name: Build and Deploy to Azure
      uses: Azure/static-web-apps-deploy@v1
      with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_PEBBLE_08050A31E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (e.g., PR comments)
          action: "upload"
          app_location: "/" # Update this if your app is in a subfolder
          api_location: "" # Leave blank if you don't have an API
          output_location: ".next" # Replace "out" with your actual build output folder (e.g., ".next" for Next.js)

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
    - name: Close Pull Request
      uses: Azure/static-web-apps-deploy@v1
      with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_PEBBLE_08050A31E }}
          action: "close"
          app_location: "/"

